import Link from "next/link"
import "./globals.css"
import { Inter } from "next/font/google"
import { Analytics } from "@/components/analytics"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-secondary-100 text-secondary-900 ${inter.className}`}
      >
        <div className="max-w-2xl mx-auto py-10 px-4">
          <header>
            <div className="flex items-center justify-between">
              <nav className="ml-auto text-sm font-medium space-x-6">
                <Link href="/" className="text-primary-500 hover:text-primary-700">Home</Link>
                <Link href="/about" className="text-primary-500 hover:text-primary-700">About</Link>
              </nav>
            </div>
          </header>
          <main>{children}</main>
        </div>
        <Analytics />
      </body>
    </html>
  )
}